version: '3.5'

services:
  webapp:
    build:
      context: ./
    image: felubra/city-playlist-suggester:1.0
    env_file: .env.local
    environment:
      APP_ENV: prod
    tmpfs:
      - /tmp
    restart: always
    networks:
      - web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`$DOMAIN`)"
      - "traefik.docker.network=web"

  reverse-proxy:
    image: "traefik:v2.2"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      - web
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  cache:
    image: "redis:6.0.8"
    restart: always
    container_name: cache
    networks:
      - internal

networks:
  web:
    name: web
  internal:
    name: internal
